
runtime! debian.vim
if has("syntax")
  syntax on
endif

scriptencoding utf-8
set encoding=utf-8
set tabstop=8 shiftwidth=8
set autoindent
set smartindent
set cindent
set number
set list
set listchars=tab:!·,trail:·
syntax enable

"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

command! Bettyf call BettyFunc()
command! Bettys call BettyStruct()

function! BettyFunc()
    let text = "/**\nfunction_name - desc\n@parameterx: desc param\n\nDescription:...\nReturn:...\n*/"
    execute "normal! i" . text
endfunction

function! BettyStruct()
    let text = "/**\nstruct my_struct - Short description\n@a: First member\n\nDescription: Longer description\n*/"
    execute "normal! i" . text
endfunction