
" INIT "
runtime! debian.vim
if has("syntax")
  syntax on
endif

" PARAMETERS "
scriptencoding utf-8
set encoding=utf-8
set tabstop=8 shiftwidth=8
set autoindent
set smartindent
set cindent
set number
set list
set listchars=tab:!·,trail:·
syntax enable
set showcmd	
set showmatch

filetype plugin on
set omnifunc=syntaxcomplete#Complete

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" CUSTOM COMMANDS "
command! Bettyf call BettyFunc()
command! Bettys call BettyStruct()

function! BettyFunc()
    let text = "/**\nfunction_name - desc\n@parameterx: desc param\n\nDescription:...\nReturn:...\n*/"
    execute "normal! i" . text
endfunction

function! BettyStruct()
    let text = "/**\nstruct my_struct - Short description\n@a: First member\n\nDescription: Longer description\n*/"
    execute "normal! i" . text
endfunction

" PLUGIN "
set nocompatible
filetype off
set rtp+=/root/.vim/bundle/Vundle.vim

call vundle#begin()
  Plugin 'VundleVim/Vundle.vim'
  Plugin 'xavierd/clang_complete'
  Plugin 'ycm-core/YouCompleteMe'
call vundle#end()

filetype plugin indent on
let g:clang_library_path='/usr/lib/llvm-14/lib/libclang.so.1'